# Generated by Django 5.2.4 on 2025-08-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parents_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
