# Generated by Django 5.2.4 on 2025-08-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_parents_name_student_parents_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
