# Generated by Django 5.2.4 on 2025-08-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teacher_alter_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sub_montant',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_payed',
            field=models.BooleanField(null=True),
        ),
    ]
