# Generated by Django 5.2.4 on 2025-08-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_student_sub_montant_student_sub_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sub_montant',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Subscription Amount'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub_payed',
            field=models.BooleanField(null=True, verbose_name='Subscription Paid'),
        ),
    ]
