# Generated by Django 5.2.4 on 2025-08-28 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_student_sub_montant_alter_student_sub_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('primaire', 'Primaire'), ('cem', 'Cem'), ('lycee', 'Lycee')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('scientifique', 'Sientifique'), ('math', 'Math'), ('math technique', 'Math Technique'), ('gestion', 'Gestion'), ('langue', 'Langue'), ('philo', 'Philo')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studylevel',
            name='name',
        ),
        migrations.AddField(
            model_name='studylevel',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studylevel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
        migrations.AddField(
            model_name='studylevel',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.speciality'),
        ),
    ]
