# Generated by Django 5.2.4 on 2025-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_school_speciality_remove_studylevel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_orphan',
            field=models.BooleanField(null=True),
        ),
    ]
