# Generated by Django 5.2.4 on 2025-08-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_student_is_orphan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(choices=[('scientifique', 'Sientifique'), ('math', 'Math'), ('math technique', 'Math Technique'), ('gestion', 'Gestion'), ('langue', 'Langue'), ('philo', 'Philo'), ('aucune', 'Aucune')], max_length=50, null=True),
        ),
    ]
